/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;

/**
 *
 * @author rafinha
 */
public class TelaSelecao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaSelecao.class.getName());

    /**
     * Creates new form TelaSelecao
     */
    public TelaSelecao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArthur = new javax.swing.JButton();
        btnJohn = new javax.swing.JButton();
        btnSadie = new javax.swing.JButton();
        btnDutch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArthur.setText("Arthur Morgan");
        btnArthur.addActionListener(this::btnArthurActionPerformed);

        btnJohn.setText("John Marston");
        btnJohn.addActionListener(this::btnJohnActionPerformed);

        btnSadie.setText("Sadie Adler");
        btnSadie.addActionListener(this::btnSadieActionPerformed);

        btnDutch.setText("Dutch van der Linde");
        btnDutch.addActionListener(this::btnDutchActionPerformed);

        jLabel1.setText("Escolha seu personagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDutch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnJohn)
                            .addComponent(btnArthur)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSadie)))))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnArthur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJohn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSadie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDutch)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDutchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDutchActionPerformed
        Personagem escolhido = new DutchVanDerLinde();
java.util.List<Personagem> oponentes = new java.util.ArrayList<>();
oponentes.add(new ArthurMorgan());
oponentes.add(new JohnMarston());
oponentes.add(new SadieAdler());
new TelaBatalha(escolhido, oponentes).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnDutchActionPerformed

    private void btnArthurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArthurActionPerformed
        Personagem escolhido = new ArthurMorgan();
java.util.List<Personagem> oponentes = new java.util.ArrayList<>();
oponentes.add(new JohnMarston());
oponentes.add(new SadieAdler());
oponentes.add(new DutchVanDerLinde());
new TelaBatalha(escolhido, oponentes).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnArthurActionPerformed

    private void btnJohnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJohnActionPerformed
        Personagem escolhido = new JohnMarston();
java.util.List<Personagem> oponentes = new java.util.ArrayList<>();
oponentes.add(new ArthurMorgan());
oponentes.add(new SadieAdler());
oponentes.add(new DutchVanDerLinde());
new TelaBatalha(escolhido, oponentes).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnJohnActionPerformed

    private void btnSadieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSadieActionPerformed
        Personagem escolhido = new SadieAdler();
java.util.List<Personagem> oponentes = new java.util.ArrayList<>();
oponentes.add(new ArthurMorgan());
oponentes.add(new JohnMarston());
oponentes.add(new DutchVanDerLinde());
new TelaBatalha(escolhido, oponentes).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnSadieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaSelecao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArthur;
    private javax.swing.JButton btnDutch;
    private javax.swing.JButton btnJohn;
    private javax.swing.JButton btnSadie;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
