/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;

/**
 *
 * @author rafinha
 */
public class TelaBatalha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaBatalha.class.getName());

    /**
     * Creates new form TelaBatalha
     */
    private Personagem jogador;
private java.util.List<Personagem> oponentes;
private int indiceOponenteAtual;
private Personagem oponenteAtual;

public TelaBatalha(Personagem jogador, java.util.List<Personagem> oponentes) {
    initComponents();
    this.jogador = jogador;
    this.oponentes = oponentes;
    this.indiceOponenteAtual = 0;
    proximoOponente();
}

private void proximoOponente() {
    if (indiceOponenteAtual >= oponentes.size()) {
        areaLog.append("\nVocê venceu todos os oponentes! Parabéns!\n");
        desabilitarBotoes();
        return;
    }
    oponenteAtual = oponentes.get(indiceOponenteAtual);
    atualizarTela();
    areaLog.append("\nUm novo oponente apareceu: " + oponenteAtual.getNome() + "!\n");
}

private void atualizarTela() {
    lblNomeJogador.setText(jogador.getNome() + " (" + jogador.getVidaAtual() + "/" + jogador.getVidaMaxima() + ")");
    lblNomeOponente.setText(oponenteAtual.getNome() + " (" + oponenteAtual.getVidaAtual() + "/" + oponenteAtual.getVidaMaxima() + ")");
    barraVidaJogador.setMaximum(jogador.getVidaMaxima());
    barraVidaJogador.setValue(jogador.getVidaAtual());
    barraVidaOponente.setMaximum(oponenteAtual.getVidaMaxima());
    barraVidaOponente.setValue(oponenteAtual.getVidaAtual());
    btnHabilidade1.setText(jogador.getNomeHabilidade1());
    btnHabilidade2.setText(jogador.getNomeHabilidade2());
}

private void desabilitarBotoes() {
    btnAtaque.setEnabled(false);
    btnHabilidade1.setEnabled(false);
    btnHabilidade2.setEnabled(false);
}

private void turnoDoOponente() {
    if (oponenteAtual.isTurnoPreso()) {
        areaLog.append(oponenteAtual.getNome() + " está preso e perdeu o turno!\n");
        oponenteAtual.liberarTurno();
        return;
    }
    int acao = (int) (Math.random() * 3);
    if (acao == 0) {
        oponenteAtual.atacar(jogador);
        areaLog.append(oponenteAtual.getNome() + " atacou!\n");
    } else if (acao == 1) {
        oponenteAtual.usarHabilidade1(jogador);
        areaLog.append(oponenteAtual.getNome() + " usou " + oponenteAtual.getNomeHabilidade1() + "!\n");
    } else {
        oponenteAtual.usarHabilidade2(jogador);
        areaLog.append(oponenteAtual.getNome() + " usou " + oponenteAtual.getNomeHabilidade2() + "!\n");
    }
}

private void verificarFimDeTurno() {
    atualizarTela();
    if (!oponenteAtual.estaVivo()) {
        areaLog.append(oponenteAtual.getNome() + " foi derrotado!\n");
        indiceOponenteAtual++;
        proximoOponente();
        return;
    }
    turnoDoOponente();
    atualizarTela();
    if (!jogador.estaVivo()) {
        areaLog.append("Você foi derrotado! Fim de jogo.\n");
        desabilitarBotoes();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeJogador = new javax.swing.JLabel();
        lblNomeOponente = new javax.swing.JLabel();
        barraVidaOponente = new javax.swing.JProgressBar();
        barraVidaJogador = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        btnAtaque = new javax.swing.JButton();
        btnHabilidade1 = new javax.swing.JButton();
        btnHabilidade2 = new javax.swing.JButton();
        btnCura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeJogador.setText("Seu Personagem");

        lblNomeOponente.setText("Oponente");

        areaLog.setColumns(20);
        areaLog.setRows(5);
        areaLog.setText("Batalha iniciada!");
        jScrollPane1.setViewportView(areaLog);

        btnAtaque.setText("Ataque Normal");
        btnAtaque.addActionListener(this::btnAtaqueActionPerformed);

        btnHabilidade1.setText("Habilidade 1");
        btnHabilidade1.addActionListener(this::btnHabilidade1ActionPerformed);

        btnHabilidade2.setText("Habilidade 2");
        btnHabilidade2.addActionListener(this::btnHabilidade2ActionPerformed);

        btnCura.setText("Cura");
        btnCura.addActionListener(this::btnCuraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNomeJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeOponente)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraVidaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barraVidaOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHabilidade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCura))
                            .addComponent(btnHabilidade1))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeJogador)
                    .addComponent(lblNomeOponente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraVidaOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraVidaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnAtaque)
                .addGap(18, 18, 18)
                .addComponent(btnHabilidade1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHabilidade2)
                    .addComponent(btnCura))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtaqueActionPerformed
        jogador.atacar(oponenteAtual);
areaLog.append(jogador.getNome() + " atacou " + oponenteAtual.getNome() + "!\n");
verificarFimDeTurno();
    }//GEN-LAST:event_btnAtaqueActionPerformed

    private void btnHabilidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidade1ActionPerformed
        jogador.usarHabilidade1(oponenteAtual);
areaLog.append(jogador.getNome() + " usou " + jogador.getNomeHabilidade1() + "!\n");
verificarFimDeTurno();
    }//GEN-LAST:event_btnHabilidade1ActionPerformed

    private void btnHabilidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidade2ActionPerformed
      jogador.usarHabilidade2(oponenteAtual);
areaLog.append(jogador.getNome() + " usou " + jogador.getNomeHabilidade2() + "!\n");
verificarFimDeTurno();
    }//GEN-LAST:event_btnHabilidade2ActionPerformed

    private void btnCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuraActionPerformed
        jogador.curar();
areaLog.append(jogador.getNome() + " se curou!\n");
verificarFimDeTurno();
    }//GEN-LAST:event_btnCuraActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JProgressBar barraVidaJogador;
    private javax.swing.JProgressBar barraVidaOponente;
    private javax.swing.JButton btnAtaque;
    private javax.swing.JButton btnCura;
    private javax.swing.JButton btnHabilidade1;
    private javax.swing.JButton btnHabilidade2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeJogador;
    private javax.swing.JLabel lblNomeOponente;
    // End of variables declaration//GEN-END:variables
}
